### ISSUE TITLE
Venue

### ISSUE THREAD

**Issue by plexus** [euruject/euruject#1]
We need a place! My personal ideas for requirements
- room (desk/tables/chairs) for at least 100 people
- wifi
- free/cheap

(Very) nice to have
- rooms for talks/workshops, ideally with screen/projector

Suggested so far 
- bitcrowd
- betahous
- [Supermarkt Berlin](http://www.supermarkt-berlin.net/en)
- immobilienscout
- HERE (nokia maps)
- co_up
- soundcloud (old offices after move?)

**Comment by plexus** [comment]
I'm in touch with Bitcrowd and it sounds like they're interested, but will need some time to get confirmation. Haven't contacted any of the others yet, so if you know someone there, or are good at cold calling/mailing, then pick one, go ahead and report here.

Bitcrowd has space for 100 people plus side rooms. They also suggested the idea of doing a Neukolln-hopping tour involving a couple different companies in Neukolln. I think that would be really cool :)

**Comment by xamebax** [comment]
Neukoelln-hopping sounds great! But would that mean extending the conf for the whole day?

**Comment by plexus** [comment]
I was kind of assuming it would be one day full day thing. What did you
have in mind?

**Comment by xamebax** [comment]
I don't mind either way, but I was just making sure. A full day sounds cool!

**Comment by rentalcustard** [comment]
Tempelhof. Open Air.

**Comment by plexus** [comment]
Not bad! Does pose some logistical challenges...

2014-05-15 20:40 GMT+08:00 Tom Stuart notifications@github.com:

> Tempelhof. Open Air.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/euruject/euruject/issues/1#issuecomment-43203933
> .

## 

| @plexus https://twitter.com/plexus  | arnebrasseur.net | The Happy
Lambda https://leanpub.com/happylambda |

**Comment by pxlpnk** [comment]
I like the Open Air idea
we could make an offline conf out if it where you have no slides and just need to explain whats going on. also no phones.

**Comment by plexus** [comment]
Not sure if you guys are taking the #trollconf approach or actually serious :)

I got green light from Bitcrowd though, thanks to @bitboxer and his colleagues!

:heart::heartpulse::heartbeat::two_hearts::sparkling_heart::revolving_hearts::cupid::gift_heart::yellow_heart::blue_heart::purple_heart::green_heart::heart::heartpulse::heartbeat::two_hearts::sparkling_heart::revolving_hearts::cupid::gift_heart::yellow_heart::blue_heart::purple_heart::green_heart::heart::heartpulse::heartbeat::two_hearts::sparkling_heart::revolving_hearts::cupid::gift_heart::yellow_heart::blue_heart::purple_heart::green_heart::heart::heartpulse::heartbeat::two_hearts::sparkling_heart::revolving_hearts::cupid::gift_heart::yellow_heart::blue_heart::purple_heart::green_heart::heart::heartpulse::heartbeat::two_hearts::sparkling_heart::revolving_hearts::cupid::gift_heart::yellow_heart::blue_heart::purple_heart::green_heart::heart::heartpulse::heartbeat::two_hearts::sparkling_heart::revolving_hearts::cupid::gift_heart::yellow_heart::blue_heart::purple_heart::green_heart::heart::heartpulse::heartbeat::two_hearts::sparkling_heart::revolving_hearts::cupid::gift_heart::yellow_heart::blue_heart::purple_heart::green_heart::heart::heartpulse::heartbeat::two_hearts::sparkling_heart::revolving_hearts::cupid::gift_heart::yellow_heart::blue_heart::purple_heart::green_heart::heart::heartpulse::heartbeat::two_hearts::sparkling_heart::revolving_hearts::cupid::gift_heart::yellow_heart::blue_heart::purple_heart::green_heart::heart::heartpulse::heartbeat::two_hearts::sparkling_heart::revolving_hearts::cupid::gift_heart::yellow_heart::blue_heart::purple_heart::green_heart::heart::heartpulse::heartbeat::two_hearts::sparkling_heart::revolving_hearts::cupid::gift_heart::yellow_heart::blue_heart::purple_heart::green_heart::heart::heartpulse::heartbeat::two_hearts::sparkling_heart::revolving_hearts::cupid::gift_heart::yellow_heart::blue_heart::purple_heart::green_heart::heart::heartpulse::heartbeat::two_hearts::sparkling_heart::revolving_hearts::cupid::gift_heart::yellow_heart::blue_heart::purple_heart::green_heart::heart::heartpulse::heartbeat::two_hearts::sparkling_heart::revolving_hearts::cupid::gift_heart::yellow_heart::blue_heart::purple_heart::green_heart::heart::heartpulse::heartbeat::two_hearts::sparkling_heart::revolving_hearts::cupid::gift_heart::yellow_heart::blue_heart::purple_heart::green_heart::heart::heartpulse::heartbeat::two_hearts::sparkling_heart::revolving_hearts::cupid::gift_heart::yellow_heart::blue_heart::purple_heart::green_heart::heart::heartpulse::heartbeat::two_hearts::sparkling_heart::revolving_hearts::cupid::gift_heart::yellow_heart::blue_heart::purple_heart::green_heart::heart::heartpulse::heartbeat::two_hearts::sparkling_heart::revolving_hearts::cupid::gift_heart::yellow_heart::blue_heart::purple_heart::green_heart::heart::heartpulse::heartbeat::two_hearts::sparkling_heart::revolving_hearts::cupid::gift_heart::yellow_heart::blue_heart::purple_heart::green_heart::heart::heartpulse::heartbeat::two_hearts::sparkling_heart::revolving_hearts::cupid::gift_heart::yellow_heart::blue_heart::purple_heart::green_heart::heart::heartpulse::heartbeat::two_hearts::sparkling_heart::revolving_hearts::cupid::gift_heart::yellow_heart::blue_heart::purple_heart::green_heart::heart::heartpulse::heartbeat::two_hearts::sparkling_heart::revolving_hearts::cupid::gift_heart:

Regarding the Neukölln-hopping and feeding back into #3, maybe we can reach out to companies in the neighbourhood, and ask if they want to act as "overflow", i.e. when the bitcrowd office fills up and their's still more people joining, we could open up another place and redirect people there.

**Comment by xamebax** [comment]
Whoa, cool, thanks @bitboxer and co.! I think Bitcrowd will be ok for this event.

**Comment by plexus** [comment]
Venue is official, the Bitcrowd office it is. Thanks again, Bitcrowd!
