### ISSUE TITLE
Date

### ISSUE THREAD

**Issue by plexus** [euruject/euruject#2]
eurucamp / JRubyConf.EU runs 1/2/3 August (Fri-Sun). The week before is free for activities.

So far people have expressed they would like Juli 31, I like that as well, but maybe for a really good venue we could shift the date? Anyway leaving this thread here for suggestions/discussion.

**Comment by xamebax** [comment]
I'll just point out that lightning.io will most probably take place on one weekend in August, but can't give an exact date at this moment.

**Comment by PragTob** [comment]
Seems good to me. Just please don't do the 29th ;)

**Comment by plexus** [comment]
Bitcrowd is OK with making their office available on the 31st. Is there anyone who does _not_ like this idea?

**Comment by chastell** [comment]
In case there’s suddenly a crowd of anti-July-31sters, here’s yet another vote for July 31st.

**Comment by skade** [comment]
@xamebax tangential topic, but lightning happening in August would mean 4 Ruby events in August (eurucamp, RedFrog, RailsCamp, lightning). Just saying.

**Comment by xamebax** [comment]
Yeah, I'm aware of that. We are still looking for a venue for
lighting.iobtw. I'm rooting for euruject happening on July 31st.
Hidden agenda: I'm
gonna be moving apartments on the next day (assuming I finally find one).

**Comment by plexus** [comment]
closing this as the date has been chosen: 20140731

**Comment by bitboxer** [comment]
The date in the activity is 2014/07/30 . Is this wrong? I am confused :wink:

**Comment by skade** [comment]
We were surprised as well.

**Comment by plexus** [comment]
Friday that feels like Monday... fixed. Also added a link to the repo.

2014-07-18 17:16 GMT+02:00 Florian Gilcher notifications@github.com:

> We were surprised as well.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/euruject/euruject/issues/2#issuecomment-49442590.

## 

| @plexus https://twitter.com/plexus  | arnebrasseur.net | The Happy
Lambda https://leanpub.com/happylambda |

**Comment by plexus** [comment]
Aaaaannnndddd.... updated the README as well, not sure where that 30th idea came from.
