### ISSUE TITLE
attendance

### ISSUE THREAD

**Issue by plexus** [euruject/euruject#3]
When looking for a venue people want to know how many people will come. We have no way of predicting that. There were +100 rejected speakers for eurucamp, but no telling how many of those will come, plus that's certainly not our only audience.

I think 100 is a conservative estimate. Should we ask to sign up?

Related, should we ask any money? If any it should be a token amount, I'm thinking 5-10 euro, to cover small costs. Things like tape (you always need tape :)) or as a backup if anything breaks. Of course if the venue is commercial it might have to be more but I'm still hoping for the goodwill of a company of organization to give us a free venue. Any money left could be donated to Ruby Berlin e.W.

**Comment by parndt** [comment]
Have you considered a kickstarter/pre-sell approach? This could allow for a more accurate gauge of interest by pre-selling and reduces the risks somewhat.

Is the event being run / managed by an organisation or is it personal liability?

**Comment by IvoBetke** [comment]
I think ticket should be sold at around EUR 15 to 25 for the day (ex/including) drinks and/or food e.g.
cause then people are more committed to attend the event then if its for free.

we could just run it through eventbrite or something a like

**Comment by plexus** [comment]
@parndt If we need an official entity for some things I'm sure we can reach out to Ruby Berlin e.V.

How about going completely the other way? Charge nothing, no registration, food/drinks is "bring your own". We can still "pass the hat around" to cover small costs. We establish the maximum capicity of the venue and close the doors when it's full.

**Comment by parndt** [comment]
Charging makes people more committed and generally makes for a better event, in my experience. These things are never free to organise and as an organiser it's not fun being out of pocket and spending lots of time.

**Comment by plexus** [comment]
What costs do you see? All I can think of is some tiny costs like tape and garbage bags.

**Comment by parndt** [comment]
I was mainly thinking costs for the venue, or food or wifi or such.

**Comment by plexus** [comment]
If I understood correctly we could use Bitcrowd's office for free, @bitboxer could you chime in?

Food/drinks I would like to do "BYO", maybe even a potluck. The underlying idea is to remove the distinction between participant and organizer (and vice versa). It's a collaborative effort by everyone who shows up.

**Comment by bitboxer** [comment]
The venue would be free for you. We have a big fridge we could fill with drinks for 1,50€ each. The rest is up to you to organize. If you want to have free drinks or food, you need a way to make that possible.

**Comment by chastell** [comment]
FOSDEM-style ‘no fee and no registration’ is super tempting, but I never saw it work anywhere near as good as at FOSDEM; even token fees seem to make people more likely to attend. I’m not sure euruject needs to aim at having many people around, though (esp. when there are no venue costs); even a few people interested in exchanging ideas and hacking together should make it work pretty well.

**Comment by bitboxer** [comment]
If you plan to have food or other stuff, it could become important to know how many people will attend. Keep that in mind.

**Comment by myabc** [comment]
> What costs do you see?

If you don't have to pay for venue, catering, then your biggest costs are taken care of.

> If we need an official entity for some things I'm sure we can reach out to Ruby Berlin e.V.

Should be no problem there, although @skade, @thilo and @dajana would have to decide.

**Comment by skade** [comment]
I don't see an immediate problem with running it under the e.V. flag, especially if you want to sell tickets, but lets discuss this when beginning of June, please.

**Comment by plexus** [comment]
@bitboxer and I are in favor of keeping it free. Does anyone strongly object?

We will provide drinks that people need to pay for (honour system). For lunch people should go out and enjoy some of the fine dining Neukölln has to offer.

If not many people show up, then we have little cleaning up to do. If too many people show up then we (proverbially) close the doors, full is full.

**Comment by PragTob** [comment]
Seems alright. But I want to come :) Do we have a website we can link to.

**Comment by bitboxer** [comment]
This one :wink: : http://activities.eurucamp.org/activities/7

**Comment by skade** [comment]
Is it okay if we recommend to speakers to make their way to euruject and drop them off there?

**Comment by plexus** [comment]
of course!
