### ISSUE TITLE
Schedule

### ISSUE THREAD

**Issue by plexus** [euruject/euruject#4]
Ideally I would like no pre-set schedule. Instead I'd love to something like what they do at juggling conventions

![](https://farm2.staticflickr.com/1128/1112093768_94574f258b_b.jpg)

Put up big papers with rows for the times, columns for locations (if you have multiple locations, e.g. conference rooms). People can stick post-its (or just write directly) with whatever talk/workshop/collaborative hacking they feel like doing.

What do y'all think?

**Comment by parndt** [comment]
This works well at [Rails Camp](http://railscamps.com) events

**Comment by chastell** [comment]
This seems like a good idea. I think a designated time to go out for lunch (or order stuff to the venue) might be a good idea.

**Comment by leffen** [comment]
Hey, seems like its a long time since there where activity here. Are you still planning to make this happen ?  I am in the process of buying plane tickets now so it would be nice to know :-)

**Comment by plexus** [comment]
Yes, we have a date (2014-07-31) and a location (Bitcrowd office). For an unconference that's pretty much all we need. There's still some details to work out (set up a small public website, CoC, how to handle the cleanup, etc.) but the essentials are there so feel free to book your flights :)

**Comment by leffen** [comment]
Unfortunately the only direct flight where at evening of the 31, so I will miss it ;-(

**Comment by xamebax** [comment]
Re: website - can we just do a github page, or, being very un-conference
style, write everything in the README file? ;)

2014-06-23 13:23 GMT+02:00 Leffen notifications@github.com:

> Unfortunately the only direct flight where at evening of the 31, so I will
> miss it ;-(
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/euruject/euruject/issues/4#issuecomment-46831953.

## 

Pozdrawiam,
Marta Paciorkowska

**Comment by plexus** [comment]
Github pages is totally fine. I'll set something up soon-ish, I've been meaning to get some practice with Middleman :)

**Comment by plexus** [comment]
I added some basic info to the README to have at least something to link to quickly. Have a look, see if anything important is missing.

**Comment by plexus** [comment]
Closing this in favor of #9
